### ISSUE TITLE
Related work for your paper

### ISSUE THREAD

**Issue by gklambauer** [IDEA-XL/InstructMol#2]
Dear authors,

I've just read your paper with great interest. Unfortunately, I did not find your email addresses on the paper. 

Could you please check if you should cite our recent work on aligning molecular representation and natural language: https://arxiv.org/abs/2303.03363 !  Thanks for considering!

Good luck with your article!

@article{seidl2023enhancing,
  title={Enhancing activity prediction models in drug discovery with the ability to understand human language},
  author={Seidl, Philipp and Vall, Andreu and Hochreiter, Sepp and Klambauer, G{\"u}nter},
  journal={International Conference On Machine Learning (ICML)},
  year={2023}
}

**Comment by CiaoHe** [comment]
Thx for your kind reminders, we will fix this in the next revision.
