### ISSUE TITLE
Question about Pretraining dataset

### ISSUE THREAD

**Issue by chiggly007** [IDEA-XL/InstructMol#5]
hey all, first of all great work on this! I had a couple of question regarding the pretraining data that was released here:
https://huggingface.co/datasets/OpenMol/PubChemSFT

When I look at the the train.pkl and/or the all_clean.json:

1. all the the question describes are the same "'Please describe this molecule" is that intended?
2. Based on the paper SELFIES were used instead of SMILES but the readme suggest SMILES is being used. Can you please clarify?
3. Based on the paper the training dataset would be formated like this:
{
  "graph": {
    "edge_index": [[0, 1], [1, 2], ...],
    "edge_feat": [[0, 1], [1, 2], ...],
    "node_feat": [[6, 0], [1, 2], ...],
    "num_nodes": 5
  },
  "conversations": [
    {
      "from": "human",
      "value": "Describe this molecule. The compound SELFIES sequence is: [C][O][N]."
    },
    {
      "from": "gpt",
      "value": "This molecule is carbon monoxide bonded to nitrogen."
    }
  ]
}

I dont see a reference to the SELFIES/SMILES in training files that show the optional SELFIES and/or SMILES.

thanks!

**Comment by CiaoHe** [comment]
Hi, thx for your interest.
I've checked the dataset (arrow format) here https://huggingface.co/datasets/OpenMol/PubChemSFT/tree/main/stage1 using `dataset.load_from_disk(PATH)`,
here's a sample
```python
{'molecules': {'smiles': ['C=CC(C)(C)c1[nH]cnc1C=C1NC(=O)C(C(C)C)NC1=O']},
 'messages': [{'content': 'You are a chemist. Now you are given a representation of a molecule. Please help me to understand the molecule.',
   'role': 'system'},
  {'content': '<molecule_2d> What do you know about the molecule?',
   'role': 'user'},
  {'content': '(3E,6S)-3-[[5-(2-methylbut-3-en-2-yl)-1H-imidazol-4-yl]methylidene]-6-propan-2-ylpiperazine-2,5-dione is a natural product found in Aspergillus insuetus with data available.',
   'role': 'assistant'}]}
```

you can get the molecule SMILES just from the `smiles` key. If you want to use the SELFIES format, you can refer to [selfies package tutorial about translation](https://github.com/aspuru-guzik-group/selfies?tab=readme-ov-file#translation-between-selfies-and-smiles-representations). I think it's ok for the `.arrow` part.

**Comment by CiaoHe** [comment]
And I also checked the `.pkl` files (which already converted molecule graphs into pyg graph format). We indeed not include the molecule SMILES/SELFIES information for the pkl files since  stage-1 is just an alignment stage between the 2D graph and textual modality, and we didn't want the text description part to overlook the graph part (only attend to the SMILES, if we present SMILES).

For the identical user query 'Please describe this molecule:', yes it's an issue that can be improved by augmenting the sentences with different kinds of presentation (maybe you can try it).

**Comment by chiggly007** [comment]
thank you for this information!
